# Generated by Django 4.1.5 on 2023-01-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_tags_alter_post_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(auto_created=True, max_length=250, unique=True),
        ),
    ]
